export const ActionTypes = {
  SET_USERS: 'SET_USERS',
  SELECTED_USER: 'SELECTED_USER',
  REMOVE_SELECTED_USER: 'REMOVE_SELECTED_USER',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
  ADD_BRANCH: 'ADD_BRANCH',
  EDIT_BRANCH: 'EDIT_BRANCH',
  DELETE_BRANCH: 'DELETE_BRANCH',
  ADD_MERCHANT: 'ADD_MERCHANT',
  EDIT_MERCHANT: 'EDIT_MERCHANT',
  DELETE_MERCHANT: 'DELETE_MERCHANT',
};
